version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    restart: always
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    networks:
      - planmate-network
    volumes:
      - planmate-volume:/var/lib/postgresql/data

  backend:
    image: 'iliandocker/planmate-docker-repo:planmate-backend'
    container_name: planmate-backend
    restart: always
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
      - 'SPRING_PROFILES_ACTIVE=docker' 
      - 'JWT_SECRET=${JWT_SECRET}'
    networks:
      - planmate-network
    depends_on:
      - postgres

  frontend:
    image: 'iliandocker/planmate-docker-repo:planmate-frontend'
    container_name: planmate-frontend
    restart: always
    networks:
      - planmate-network
    depends_on:
      - backend
    ports:
      - "80:80" 

volumes:
  planmate-volume:
    driver: local

networks:
  planmate-network:
    name: planmate-network
    driver: bridge