spring.application.name=planmate
# Use an env var to toggle profiles (local, docker, prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.servlet.context-path=/

# Hibernate & Database Config
spring.datasource.driver-class-name=org.postgresql.Driver

# This will automatically switch between 'postgres' (for docker) or 'localhost' (for local dev)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Spring Security & JWT
application.security.disabled=${SECURITY_DISABLED:false}
# NEVER hardcode the real secret here. 
# In production, this must be a long random string provided via Environment Variables.
jwt.secret=${JWT_SECRET:dev_secret_only_for_local_testing}